package groovy
/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import groovy.Library
import groovy.util.logging.Log
import spock.lang.Specification

@Log
class LibraryTest extends Specification {


    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Library()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true

    }

    @BlackBox
    def test() {
        setup:
        log.fine("test")

        when:
        null

        then:
        true

    }
}
